services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2181:2888;zookeeper2:2182:2889;zookeeper3:2183:2890
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"
    ports:
      - "2181:2181"
      - "2888:2888"
  zookeeper2: # hostname -> zookeeper2:2181
    image: confluentinc/cp-zookeeper:latest
    environment:
      # clientPort
      ZOOKEEPER_CLIENT_PORT: 2181 # default
      # server id
      ZOOKEEPER_SERVER_ID: 2 # max 3
      # zookeepers servers
      ZOOKEEPER_SERVERS: zookeeper:2181:2888;zookeeper2:2182:2889;zookeeper3:2183:2890
      # ruok stat
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"
    ports:
      - "2182:2181"
      - "2889:2888"
  zookeeper3: # hostname -> zookeeper3:2181
    image: confluentinc/cp-zookeeper:latest
    environment:
      # clientPort
      ZOOKEEPER_CLIENT_PORT: 2181 # default
      # server id
      ZOOKEEPER_SERVER_ID: 3 # max 3
      # zookeepers servers
      ZOOKEEPER_SERVERS: zookeeper:2181:2888;zookeeper2:2182:2889;zookeeper3:2183:2890
      # ruok stat
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"
    ports:
      - "2183:2181"
      - "2890:2888"
  vm:
    build:
      context: ./vm
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
  kafka: # hostname -> kafka:9092
    image: confluentinc/cp-kafka:latest
    restart: on-failure
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181,zookeeper2:2181,zookeeper3:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    ports:
      - "19092:19092"
      - "29092:29092"
    depends_on:
      - zookeeper
      - zookeeper2
      - zookeeper3
  kafka2: # hostname -> kafka2:9092
    image: confluentinc/cp-kafka:latest
    restart: on-failure
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19093,DOCKER://host.docker.internal:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181,zookeeper2:2181,zookeeper3:2181"
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    ports:
      - "19093:19093"
      - "29093:29093"
    depends_on:
      - zookeeper
      - zookeeper2
      - zookeeper3
  kafka3: # hostname -> kafka3:9092
    image: confluentinc/cp-kafka:latest
    restart: on-failure
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:9092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19094,DOCKER://host.docker.internal:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181,zookeeper2:2181,zookeeper3:2181"
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    ports:
      - "19094:19094"
      - "29094:29094"
    depends_on:
      - zookeeper
      - zookeeper2
      - zookeeper3