services:
  zookeeper: # hostname -> zookeeper:2181
    image: confluentinc/cp-zookeeper:latest
    environment:
      # clientPort
      ZOOKEEPER_CLIENT_PORT: 2181 # default
      # server id
      ZOOKEEPER_SERVER_ID: 1 # max 3
      # zookeepers servers
      ZOOKEEPER_SERVERS: zookeeper:2181:2888
      # ruok stat
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"
    ports:
      - "2181:2181"
      - "2888:2888"
  kafka-1: # hostname -> kafka-1:9092
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "19092:19092" # 127.0.0.1:19092
      - "29092:29092"
  vm:
    build:
      context: ./vm
      dockerfile: Dockerfile
    stdin_open: true
    tty: true